name=Linker
version=2.0.0
author=DeveloperSungHyun <sunghyun5322@gmail.com>
maintainer=DeveloperSungHyun <sunghyun5322@gmail.com>
sentence=Communication library for connecting Arduino and ESP32 boards with the Linker Android application.
paragraph=This library provides a custom communication protocol interface for the Linker Android app. It supports seamless data exchange over Bluetooth/Serial and is optimized for both standard Arduino AVR boards and high-performance ESP32 series.
category=Communication
url=https://github.com/han-sunghyun/Arduino_Linker_Library
architectures=*